"""milestone_13_analysis_runs

Revision ID: 04be6ca41afa
Revises: 8da274cdacf2
Create Date: 2026-09-09 07:51:56.669642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04be6ca41afa'
down_revision: Union[str, Sequence[str], None] = '8da274cdacf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('log_evidence_id', sa.UUID(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('result_text', sa.String(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('effort', sa.String(length=20), nullable=True),
    sa.Column('skill_name', sa.String(length=100), nullable=True),
    sa.Column('skill_version', sa.String(length=20), nullable=True),
    sa.Column('input_manifest_sha256', sa.String(length=64), nullable=True),
    sa.Column('output_sha256', sa.String(length=64), nullable=True),
    sa.Column('current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['log_evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.add_column('jobs', sa.Column('incident_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'incidents', ['incident_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'incident_id')
    op.drop_table('analysis_runs')
    # ### end Alembic commands ###
