"""milestone 11 jobs table

Revision ID: 8da274cdacf2
Revises: 6c3160c80adc
Create Date: 2026-09-09 05:51:05.452177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8da274cdacf2'
down_revision: Union[str, Sequence[str], None] = '6c3160c80adc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('effort', sa.String(length=20), nullable=True),
    sa.Column('skill_name', sa.String(length=100), nullable=True),
    sa.Column('skill_version', sa.String(length=20), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
