"""AI cost-optimization mission Phase 2, Issue 6: unit tests for the
deterministic daily-report assembly step — no Docker/Postgres/RabbitMQ
needed, unlike the rest of bridge/tests/test_bridge.py, since this only
exercises pure functions.

These prove the core Issue 6 claims: Claude's compact output supplies
only the shift-level overview and cross-incident findings; every other
field (title, per-incident status/grafana_url/log_filename/screenshots/
existing analysis) is carried through verbatim from the frozen snapshot,
never regenerated by or round-tripped through Claude.
"""
from __future__ import annotations

import pytest

from noc_bridge.service import _merge_daily_report
from noc_bridge.validation import OutputValidationError, validate_merged_daily_report, validate_output

_SNAPSHOT = {
    "shift_id": "11111111-1111-1111-1111-111111111111",
    "shift_starts_at": "2026-09-13T00:00:00+00:00",
    "shift_ends_at": "2026-09-13T08:00:00+00:00",
    "incidents": [
        {
            "id": "22222222-2222-2222-2222-222222222222",
            "display_id": "INC-001",
            "title": "Payment service errors",
            "status": "RESOLVED",
            "grafana_url": "https://grafana.example/d/abc",
            "log_filename": "payments.log",
            "screenshots": [{"bucket": "noc-evidence", "object_key": "k1", "filename": "s1.png"}],
            "analysis": {
                "summary_en": "NullPointerException in PaymentWorker",
                "summary_zh": "支付服务空指针异常",
                "key_finds": [
                    {
                        "label_en": "NullPointerException", "label_zh": "空指针异常",
                        "detail_en": "in PaymentWorker.charge", "detail_zh": "在 PaymentWorker.charge 中",
                        "count": 5, "percentage": 100.0,
                    }
                ],
                "secondary_finds": [],
                "likely_cause_en": "null pointer", "likely_cause_zh": "空指针",
                "recommended_action_en": "patch", "recommended_action_zh": "修复",
                "severity_signal": "high",
                "confidence": 0.8,
            },
        },
        {
            "id": "33333333-3333-3333-3333-333333333333",
            "display_id": "INC-002",
            "title": "Unanalyzed incident",
            "status": "OPEN",
            "grafana_url": None,
            "log_filename": None,
            "screenshots": [],
            "analysis": None,
        },
    ],
}

_AI_OUTPUT = {
    "overview_en": "Two incidents this shift, one high severity.",
    "overview_zh": "本班次两起事件，一起高严重性。",
    "cross_incident_findings_en": "No cross-incident correlation was found; these incidents appear unrelated.",
    "cross_incident_findings_zh": "未发现跨事件关联；这些事件似乎不相关。",
}


def test_merge_carries_through_per_incident_fields_verbatim_not_from_ai():
    merged = _merge_daily_report(_SNAPSHOT, _AI_OUTPUT)
    section = merged["sections"][0]
    assert section["incident_display_id"] == "INC-001"
    assert section["title"] == "Payment service errors"
    assert section["status"] == "RESOLVED"
    assert section["grafana_url"] == "https://grafana.example/d/abc"
    assert section["log_filename"] == "payments.log"
    assert section["screenshots"] == _SNAPSHOT["incidents"][0]["screenshots"]
    # the existing analysis object is carried through byte-for-byte —
    # Claude never saw it and never regenerated it.
    assert section["analysis"] == _SNAPSHOT["incidents"][0]["analysis"]


def test_merge_handles_incident_with_no_analysis_yet():
    merged = _merge_daily_report(_SNAPSHOT, _AI_OUTPUT)
    assert merged["sections"][1]["analysis"] is None


def test_merge_uses_only_ai_overview_and_cross_incident_fields():
    merged = _merge_daily_report(_SNAPSHOT, _AI_OUTPUT)
    assert merged["overview_en"] == _AI_OUTPUT["overview_en"]
    assert merged["overview_zh"] == _AI_OUTPUT["overview_zh"]
    assert merged["cross_incident_findings_en"] == _AI_OUTPUT["cross_incident_findings_en"]
    assert merged["cross_incident_findings_zh"] == _AI_OUTPUT["cross_incident_findings_zh"]


def test_merge_computes_a_deterministic_title_not_from_ai():
    merged = _merge_daily_report(_SNAPSHOT, _AI_OUTPUT)
    assert "title" in merged
    assert merged["title"]
    # the AI schema (see sandbox/entrypoint.py's daily-alert-report
    # schema) doesn't even have a title field to have echoed here.
    assert "title" not in _AI_OUTPUT


def test_merged_report_passes_full_shape_validation():
    merged = _merge_daily_report(_SNAPSHOT, _AI_OUTPUT)
    validate_merged_daily_report(merged)  # must not raise


def test_ai_output_alone_fails_full_shape_validation_missing_sections():
    with pytest.raises(OutputValidationError):
        validate_merged_daily_report(_AI_OUTPUT)


def test_raw_ai_compact_output_passes_the_pre_merge_validator():
    # this is what validate_output("daily_report", ...) actually checks
    # against the sandbox's raw result, before any merge happens.
    validate_output("daily_report", _AI_OUTPUT)


def test_pre_merge_validator_rejects_a_full_legacy_shaped_output():
    # guards against a stale/misconfigured sandbox image silently
    # reverting to the old full-report schema (title/sections) without
    # the new compact fields.
    with pytest.raises(OutputValidationError):
        validate_output("daily_report", {"title": "x", "overview_en": "x", "overview_zh": "x", "sections": []})
